# Stage 1: Build the Angular app
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve with nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist/pos_master_web/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
